# (C) Ivan Mercep <ivan.merchep@gmail.com>

FILE ( READ version.txt VERSION_TXT )
STRING ( STRIP "${VERSION_TXT}" VERSION_TXT )
STRING ( REGEX MATCHALL "^([0-9]+)\\.([0-9]+)\\.([0-9]+)-([0-9]+)$" OUTPUT ${VERSION_TXT} )

SET ( VER_MAJOR	${CMAKE_MATCH_1} )
SET ( VER_MINOR	${CMAKE_MATCH_2} )
SET ( VER_PATCH	${CMAKE_MATCH_3} )
SET ( VER_COMMIT ${CMAKE_MATCH_4} )

SET ( VERSION ${VER_MAJOR}.${VER_MINOR}.${VER_PATCH}-${VER_COMMIT} )
MESSAGE ( "Building version: ${VERSION}" )

ADD_DEFINITIONS ( -DVERSION="${VERSION}" )
